
#log4z

#section name is logger key
#path: default is ./log/
#level: must in "ALL, DEBUG, INFO, WARN, ERROR, ALARM, FATAL". that is log output level.
#display: default is true, that is display to screen.
#monthdir default is false, that is no month directory.
#limitsize default is 100, that is one log file limite 100M
#fileline default is true, that is record log with location filename and line  number
#enable default is true, that is stop or start one logger.
#outfile default is true, that is output to file.

[Main]
path=./log/
level = ALL
display = false
monthdir = true
fileline = true
#enable = false
#outfile = false

[db]
path = ./log/
level=ALL
display=false
monthdir = true
#enable = false
limitsize=20
#
#
#
#
